### ISSUE TITLE
HTTP request sent, awaiting response... 404 Not Found 2019-06-05 07:57:37 ERROR 404: Not Found.

### ISSUE THREAD

**Issue by hunterhe** [breakwa2333/v2ray-onekey#1]
似乎创建文件夹失败了

2019-06-05 07:57:37 ERROR 404: Not Found.

  End-of-central-directory signature not found.  Either this file is not
  a zipfile, or it constitutes one disk of a multi-part archive.  In the
  latter case the central directory and zipfile comment will be found on
  the last disk(s) of this archive.
unzip:  cannot find zipfile directory in one of /home/webtemp/2.zip or
        /home/webtemp/2.zip.zip, and cannot find /home/webtemp/2.zip.ZIP, period.
Archive:  /home/webtemp/2.zip
[错误]  web 站点伪装 失败

**Comment by breakwa2333** [comment]
Sorry, I miswritten the download path. Now I fixed it.
