### ISSUE TITLE
报错

### ISSUE THREAD

**Issue by karr2526** [breakwa2333/v2ray-onekey#5]
bash <(curl -L -s dos2unix https://raw.githubusercontent.com/breakwa2333/v2ray-onekey/master/install.sh) | tee v2ray_ins.log
/dev/fd/63: line 1: ﻿#!/bin/bash: No such file or directory
/dev/fd/63: line 346: syntax error near unexpected token `}'
/dev/fd/63: line 346: `}'

**Comment by breakwa2333** [comment]
请问使用了什么系统？最近添加了每日定时重启，增加稳定性。

**Comment by breakwa2333** [comment]
已修复，忘记加fi
